<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

  <xacro:include filename="$(find romea_mobile_base_description)/urdf/common.xacro" />
  <xacro:include filename="$(find romea_mobile_base_description)/urdf/wheel.xacro" />
  <xacro:include filename="$(find romea_mobile_base_description)/urdf/wheel_steered.xacro" />
  <xacro:include filename="$(find romea_mobile_base_description)/urdf/axle_steering.xacro" />

  <xacro:macro name="chassis" params="*visual_chassis *visual_front_steering *visual_front_wheel *visual_rear_wheel">

    <xacro:common>
      <xacro:insert_block name="visual_chassis"/>
    </xacro:common>

    <xacro:axle_steering parent_link="${base_link}"
                         axle_steering_link="${front_axle_steering_link}"
                         axle_steering_joint="${front_axle_steering_joint}"
                         steering_link_mass="${front_axle_steering_link_mass}"
                         steering_link_x="${front_axle_steering_link_x}"
                         steering_link_y="${front_axle_steering_link_y}"
                         steering_link_z="${front_axle_steering_link_z}">
       <origin xyz="${wheelbase/2-body_reference_x} 0 ${front_wheel_radius - chassis_height}" rpy="0 0 0" />
    </xacro:axle_steering>

    <xacro:wheel_steered parent_link="${base_link}"
                         wheel_steering_link="${front_left_wheel_steering_link}"
                         wheel_steering_joint="${front_left_wheel_steering_joint}"
                         steering_link_mass="${front_wheel_steering_link_mass}"
                         steering_link_xz="${front_wheel_steering_link_xz}"
                         steering_link_y="${front_wheel_steering_link_y}"
                         wheel_spinning_link="${front_left_wheel_spinning_link}"
                         wheel_spinning_joint="${front_left_wheel_spinning_joint}"
                         wheel_origin_y="${front_hub_carrier_offset}"
                         wheel_mass="${front_wheel_mass}"
                         wheel_width="${front_wheel_width}"
                         wheel_radius="${front_wheel_radius}"
                         left_right="-1">
       <origin xyz="${wheelbase/2-body_reference_x} ${front_track/2} ${front_wheel_radius - chassis_height}" rpy="0 0 0" />
       <xacro:insert_block name="visual_front_steering"/>
       <xacro:insert_block name="visual_front_wheel"/>
     </xacro:wheel_steered>

     <xacro:wheel_steered parent_link="${base_link}"
                          wheel_steering_link="${front_right_wheel_steering_link}"
                          wheel_steering_joint="${front_right_wheel_steering_joint}"
                          steering_link_mass="${front_wheel_steering_link_mass}"
                          steering_link_xz="${front_wheel_steering_link_xz}"
                          steering_link_y="${front_wheel_steering_link_y}"
                          wheel_spinning_link="${front_right_wheel_spinning_link}"
                          wheel_spinning_joint="${front_right_wheel_spinning_joint}"
                          wheel_origin_y="${-front_hub_carrier_offset}"
                          wheel_mass="${front_wheel_mass}"
                          wheel_width="${front_wheel_width}"
                          wheel_radius="${front_wheel_radius}"
                          left_right="1">
       <origin xyz="${wheelbase/2-body_reference_x} ${-front_track/2} ${front_wheel_radius - chassis_height}" rpy="0 0 0" />
       <xacro:insert_block name="visual_front_steering"/>
       <xacro:insert_block name="visual_front_wheel"/>
     </xacro:wheel_steered>

     <xacro:wheel parent_link="${base_link}"
                  wheel_spinning_link="${rear_left_wheel_spinning_link}"
                  wheel_spinning_joint="${rear_left_wheel_spinning_joint}"
                  wheel_mass="${rear_wheel_mass}"
                  wheel_width="${rear_wheel_width}"
                  wheel_radius="${rear_wheel_radius}"
                  left_right="-1">
      <origin xyz="${-wheelbase/2-body_reference_x} ${rear_track/2} ${rear_wheel_radius  - chassis_height}" rpy="${-M_PI/2} 0 0" />
      <xacro:insert_block name="visual_rear_wheel"/>
    </xacro:wheel>

    <xacro:wheel parent_link="${base_link}"
                 wheel_spinning_link="${rear_right_wheel_spinning_link}"
                 wheel_spinning_joint="${rear_right_wheel_spinning_joint}"
                 wheel_mass="${rear_wheel_mass}"
                 wheel_width="${rear_wheel_width}"
                 wheel_radius="${rear_wheel_radius}"
                 left_right="1">
      <origin xyz="${-wheelbase/2-body_reference_x} ${-rear_track/2} ${rear_wheel_radius - chassis_height}" rpy="${-M_PI/2} 0 0" />
      <xacro:insert_block name="visual_rear_wheel"/>
    </xacro:wheel>

  </xacro:macro>

</robot>
