<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

  <xacro:include filename="$(find romea_mobile_base_description)/urdf/common.xacro" />
  <xacro:include filename="$(find romea_mobile_base_description)/urdf/wheel.xacro" />

  <xacro:macro name="chassis"
    params="*visual_chassis 
            *visual_front_left_wheel 
            *visual_front_right_wheel 
            *visual_rear_left_wheel 
            *visual_rear_right_wheel">

    <xacro:common>
      <xacro:insert_block name="visual_chassis" />
    </xacro:common>

    <xacro:wheel parent_link="${base_link}"
      wheel_spinning_link="${front_left_wheel_spinning_link}"
      wheel_spinning_joint="${front_left_wheel_spinning_joint}"
      wheel_mass="${front_wheel_mass}"
      wheel_width="${front_wheel_width}"
      wheel_radius="${front_wheel_radius}"
      left_right="-1">

      <origin xyz="${wheelbase/2} ${front_track/2} ${front_wheel_radius - chassis_height}"
        rpy="${-M_PI/2} 0 0" />
      <xacro:insert_block name="visual_front_left_wheel" />
    </xacro:wheel>

    <xacro:wheel parent_link="${base_link}"
      wheel_spinning_link="${front_right_wheel_spinning_link}"
      wheel_spinning_joint="${front_right_wheel_spinning_joint}"
      wheel_mass="${front_wheel_mass}"
      wheel_width="${front_wheel_width}"
      wheel_radius="${front_wheel_radius}"
      left_right="1">
      <origin xyz="${wheelbase/2} ${-front_track/2} ${front_wheel_radius - chassis_height}"
        rpy="${-M_PI/2} 0 0" />
      <xacro:insert_block name="visual_front_right_wheel" />
    </xacro:wheel>

    <xacro:wheel parent_link="${base_link}"
      wheel_spinning_link="${rear_left_wheel_spinning_link}"
      wheel_spinning_joint="${rear_left_wheel_spinning_joint}"
      wheel_mass="${rear_wheel_mass}"
      wheel_width="${rear_wheel_width}"
      wheel_radius="${rear_wheel_radius}"
      left_right="-1">
      <origin xyz="${-wheelbase/2} ${rear_track/2} ${rear_wheel_radius - chassis_height}"
        rpy="${-M_PI/2} 0 0" />
      <xacro:insert_block name="visual_rear_left_wheel" />
    </xacro:wheel>

    <xacro:wheel parent_link="${base_link}"
      wheel_spinning_link="${rear_right_wheel_spinning_link}"
      wheel_spinning_joint="${rear_right_wheel_spinning_joint}"
      wheel_mass="${rear_wheel_mass}"
      wheel_width="${rear_wheel_width}"
      wheel_radius="${rear_wheel_radius}"
      left_right="1">
      <origin xyz="${-wheelbase/2} ${-rear_track/2} ${rear_wheel_radius - chassis_height}"
        rpy="${-M_PI/2} 0 0" />
      <xacro:insert_block name="visual_rear_right_wheel" />
    </xacro:wheel>

  </xacro:macro>

</robot>