<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:include filename="$(find romea_mobile_base_description)/urdf/base2THD.chassis.xacro" />
    <xacro:include filename="$(find romea_mobile_base_description)/ros2_control/base2THD.ros2_control.xacro"/>
    <xacro:property name="prefix" value=""/>

     <!-- Link names -->
     <xacro:property name="base_link" value="base_link" />
     <xacro:property name="base_footprint_link" value="base_footprint_link"/>
     <xacro:property name="inertial_link" value="inertial_link"/>
     <xacro:property name="left_sprocket_wheel_spinning_link" value="left_sprocket_wheel_spinning_link"/>
     <xacro:property name="right_sprocket_wheel_spinning_link" value="right_sprocket_wheel_spinning_link"/>
     <xacro:property name="front_left_idler_wheel_spinning_link" value="front_left_idler_wheel_spinning_link"/>
     <xacro:property name="front_right_idler_wheel_spinning_link" value="front_right_idler_wheel_spinning_link"/>
     <xacro:property name="rear_left_idler_wheel_spinning_link" value="rear_left_idler_wheel_spinning_link"/>
     <xacro:property name="rear_right_idler_wheel_spinning_link" value="rear_right_idler_wheel_spinning_link"/>

     <!-- Joint names -->
     <xacro:property name="base_footprint_joint" value="base_footprint_joint"/>
     <xacro:property name="inertial_joint" value="inertial_joint"/>
     <xacro:property name="left_sprocket_wheel_spinning_joint" value="left_sprocket_wheel_spinning_joint"/>
     <xacro:property name="right_sprocket_wheel_spinning_joint" value="right_sprocket_wheel_spinning_joint"/>
     <xacro:property name="front_left_idler_wheel_spinning_joint" value="front_left_idler_wheel_spinning_joint"/>
     <xacro:property name="front_right_idler_wheel_spinning_joint" value="front_right_idler_wheel_spinning_joint"/>
     <xacro:property name="rear_left_idler_wheel_spinning_joint" value="rear_left_idler_wheel_spinning_joint"/>
     <xacro:property name="rear_right_idler_wheel_spinning_joint" value="rear_right_idler_wheel_spinning_joint"/>

      <!-- Base Properties -->
      <xacro:property name="track_width" value="0.2" />
      <xacro:property name="track_thickness" value="0.08" />
      <xacro:property name="sprocket_wheel_radius" value="0.15" />
      <xacro:property name="sprocket_wheel_mass" value="30" />
      <xacro:property name="idler_wheel_radius" value="0.103" />
      <xacro:property name="idler_wheel_mass" value="30" />
      <xacro:property name="sprocket_wheel_x" value="-0.18" />
      <xacro:property name="sprocket_wheel_z" value="0.5" />
      <xacro:property name="ground_clearance" value="${idler_wheel_radius}"/>

      <xacro:property name="aabb_length" value="1.736" />
      <xacro:property name="aabb_width" value="0.720" />
      <xacro:property name="aabb_height" value="${1.096-ground_clearance}"/>
      <xacro:property name="aabb_center_x" value="0"/>
      <xacro:property name="aabb_center_y" value="0"/>
      <xacro:property name="aabb_center_z" value="${aabb_height/2+ground_clearance}"/>

      <xacro:property name="wheelbase" value="0.87"/>
      <xacro:property name="front_track" value="0.92"/>
      <xacro:property name="rear_track" value="0.92"/>
      <xacro:property name="track" value="${front_track}"/>

      <xacro:property name="mass_base" value="600." />
      <xacro:property name="mass_center_x" value=" 0.0" />
      <xacro:property name="mass_center_y" value=" 0.0" />
      <xacro:property name="mass_center_z" value=" 0.2" />
      <xacro:property name="body_reference_x" value="0.043" />

      <xacro:property name="maximal_track_speed" value="2.0"/>
      <xacro:property name="maximal_wheel_speed" value="${maximal_track_speed}"/>
      <xacro:property name="chassis_height" value="${idler_wheel_radius}" />

    <xacro:chassis>

        <visual>
          <geometry>
            <box size="${aabb_length} ${aabb_width} ${aabb_height}"/>
          </geometry>
          <origin xyz="${aabb_center_x-body_reference_x} ${aabb_center_y}  ${aabb_center_z-chassis_height}" rpy="0 0 0" />
          <material name="grey">
            <color rgba="0.6 0.6 0.6 1"/>
          </material>
        </visual>

        <!-- visual sprocket wheel -->
        <cylinder length="${track_width}" radius="${sprocket_wheel_radius+track_thickness}"/>
        <!-- visual idler wheel -->
        <cylinder length="${track_width}" radius="${idler_wheel_radius+track_thickness}"/>

    </xacro:chassis>

    <xacro:base_control mode="test"/>

</robot>
