<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="base_control" params="mode base_name">

    <ros2_control name="${prefix}${base_name}" type="system">

      <xacro:if value="${mode == 'live'}">
        <hardware>
          <plugin>${live_hardware_plugin}</plugin>
          <param name="wheelbase">${wheelbase}</param>
          <param name="front_track">${front_track}</param>
          <param name="rear_track">${rear_track}</param>
          <param name="front_wheel_radius">${front_wheel_radius}</param>
          <param name="rear_wheel_radius">${rear_wheel_radius}</param>
        </hardware>
      </xacro:if>

      <xacro:if value="${'simulation' in mode}">
        <hardware>
          <plugin>${simulation_hardware_plugin}</plugin>
          <param name="wheelbase">${wheelbase}</param>
          <param name="front_track">${front_track}</param>
          <param name="rear_track">${rear_track}</param>
          <param name="front_wheel_radius">${front_wheel_radius}</param>
          <param name="rear_wheel_radius">${rear_wheel_radius}</param>
        </hardware>
      </xacro:if>

      <joint name="${prefix}${front_axle_steering_joint}">
        <command_interface name="position">
          <param name="min">${-maximal_axle_steering_angle}</param>
          <param name="max">${maximal_axle_steering_angle}</param>
        </command_interface>
        <state_interface name="position" />
      </joint>

      <joint name="${prefix}${rear_axle_steering_joint}">
        <command_interface name="position">
          <param name="min">${-maximal_axle_steering_angle}</param>
          <param name="max">${maximal_axle_steering_angle}</param>
        </command_interface>
        <state_interface name="position" />
      </joint>

      <joint name="${prefix}${front_left_wheel_steering_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="position">
            <param name="min">${-maximal_wheel_steering_angle}</param>
            <param name="max">${maximal_wheel_steering_angle}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
      </joint>

      <joint name="${prefix}${front_right_wheel_steering_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="position">
            <param name="min">${-maximal_wheel_steering_angle}</param>
            <param name="max">${maximal_wheel_steering_angle}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
      </joint>

      <joint name="${prefix}${rear_left_wheel_steering_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="position">
            <param name="min">${-maximal_wheel_steering_angle}</param>
            <param name="max">${maximal_wheel_steering_angle}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
      </joint>

      <joint name="${prefix}${rear_right_wheel_steering_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="position">
            <param name="min">${-maximal_wheel_steering_angle}</param>
            <param name="max">${maximal_wheel_steering_angle}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
      </joint>

      <joint name="${prefix}${front_left_wheel_spinning_joint}">
        <command_interface name="velocity">
          <param name="min">${-maximal_wheel_speed/front_wheel_radius}</param>
          <param name="max">${maximal_wheel_speed/front_wheel_radius}</param>
        </command_interface>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${front_right_wheel_spinning_joint}">
        <command_interface name="velocity">
          <param name="min">${-maximal_wheel_speed/front_wheel_radius}</param>
          <param name="max">${maximal_wheel_speed/front_wheel_radius}</param>
        </command_interface>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${rear_left_wheel_spinning_joint}">
        <command_interface name="velocity">
          <param name="min">${-maximal_wheel_speed/rear_wheel_radius}</param>
          <param name="max">${maximal_wheel_speed/rear_wheel_radius}</param>
        </command_interface>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${rear_right_wheel_spinning_joint}">
        <command_interface name="velocity">
          <param name="min">${-maximal_wheel_speed/rear_wheel_radius}</param>
          <param name="max">${maximal_wheel_speed/rear_wheel_radius}</param>
        </command_interface>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

    </ros2_control>

  </xacro:macro>

</robot>