<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="base_control" params="mode base_name has_hardware_options:=0">

    <ros2_control name="${prefix}${base_name}" type="system">

      <xacro:if value="${mode == 'live'}">
        <hardware>
          <plugin>${live_hardware_plugin}</plugin>
          <param name="sprocket_wheel_radius">${sprocket_wheel_radius}</param>
          <param name="idler_wheel_radius">${idler_wheel_radius}</param>
          <param name="track_thickness">${track_thickness}</param>

          <xacro:if value="${has_hardware_options}">
            <xacro:insert_block name="hardware_options"/>
          </xacro:if>
        </hardware>
      </xacro:if>

      <xacro:if value="${'simulation' in mode}">
        <hardware>
          <plugin>${simulation_hardware_plugin}</plugin>
          <param name="sprocket_wheel_radius">${sprocket_wheel_radius}</param>
          <param name="idler_wheel_radius">${idler_wheel_radius}</param>
          <param name="track_thickness">${track_thickness}</param>
        </hardware>
      </xacro:if>

      <joint name="${prefix}${left_sprocket_wheel_spinning_joint}">
        <command_interface name="velocity">
          <param name="min">${-maximal_wheel_speed/(sprocket_wheel_radius+track_thickness)}</param>
          <param name="max">${maximal_wheel_speed/(sprocket_wheel_radius+track_thickness)}</param>
        </command_interface>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${right_sprocket_wheel_spinning_joint}">
        <command_interface name="velocity">
          <param name="min">${-maximal_wheel_speed/(sprocket_wheel_radius+track_thickness)}</param>
          <param name="max">${maximal_wheel_speed/(sprocket_wheel_radius+track_thickness)}</param>
        </command_interface>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${front_left_idler_wheel_spinning_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="velocity">
            <param name="min">${-maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
            <param name="max">${maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${front_right_idler_wheel_spinning_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="velocity">
            <param name="min">${-maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
            <param name="max">${maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${rear_left_idler_wheel_spinning_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="velocity">
            <param name="min">${-maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
            <param name="max">${maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>

      <joint name="${prefix}${rear_right_idler_wheel_spinning_joint}">
        <xacro:if value="${'simulation' in mode}">
          <command_interface name="velocity">
            <param name="min">${-maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
            <param name="max">${maximal_wheel_speed/(idler_wheel_radius+track_thickness)}</param>
          </command_interface>
        </xacro:if>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
      </joint>


    </ros2_control>

  </xacro:macro>

</robot>
