find_package(ament_cmake_gtest REQUIRED)

get_filename_component(TEST_DIR_SRC ${CMAKE_CURRENT_SOURCE_DIR} ABSOLUTE)
configure_file(test_helper.h.in test_helper.h)
include_directories(${CMAKE_CURRENT_BINARY_DIR})

function(add_hardware_system_test test_name)
  ament_add_gtest(${PROJECT_NAME}_${test_name} ${test_name}.cpp)
  target_link_libraries(${PROJECT_NAME}_${test_name} ${PROJECT_NAME})
endfunction()

add_hardware_system_test(test_hardware_system_interface1FAS2FWD)
add_hardware_system_test(test_hardware_system_interface1FAS2RWD)
add_hardware_system_test(test_hardware_system_interface1FAS4WD)
add_hardware_system_test(test_hardware_system_interface4WD)
add_hardware_system_test(test_hardware_system_interface2FWS2FWD)
add_hardware_system_test(test_hardware_system_interface2FWS2RWD)
add_hardware_system_test(test_hardware_system_interface2FWS4WD)
add_hardware_system_test(test_hardware_system_interface2AS2FWD)
add_hardware_system_test(test_hardware_system_interface2AS2RWD)
add_hardware_system_test(test_hardware_system_interface2AS4WD)
add_hardware_system_test(test_hardware_system_interface4WS4WD)
add_hardware_system_test(test_hardware_system_interface2TD)
add_hardware_system_test(test_hardware_system_interface2THD)
add_hardware_system_test(test_hardware_system_interface2TTD)
